### ISSUE TITLE
How to deal with the problem of polyphone ?

### ISSUE THREAD

**Issue by TanYufei** [junzew/HanTTS#1]
When I input '银行'， the result of pinyin is 'yin xing' ,while the correct result is 'yin hang'.

**Comment by junzew** [comment]
Hi,
could you please give me a detailed description of how you are using the application or the steps to reproduce the bug? When I ran main.py and enter '银行', the pinyin I got from the console is ['yin2', 'hang2'], which appears to be correct. 

您好，
能否详细描述一下您使用的情景或复现这个bug的步骤？我运行main.py输入'银行'后，终端上显示的拼音是['yin2', 'hang2']，应该没有错.

**Comment by TanYufei** [comment]
您好，
我试了一下，是pypinyin识别多音字时，有的会识别错误
