### ISSUE TITLE
生成的音频播放没声音

### ISSUE THREAD

**Issue by Dawson-huang** [junzew/HanTTS#2]
您好，请问生成的音频没有声音有解决的办法吗

**Comment by junzew** [comment]
请详细说明一下情况，是网页版还是本地？另外请告知使用的浏览器或操作系统，以及生成音频的步骤？

**Comment by Dawson-huang** [comment]
已经解决了，问题在于下载下来的音频数据 syllables.zip解压后路径有两层，而源码中的synthesize函数路径只有一层，导致语音合成的时候没有音色库数据，所以生成的音频没有声音

**Comment by junzew** [comment]
syllables.zip应该解压到HanTTS目录下，我会更新README相关部分
