### ISSUE TITLE
Centos 配置不好

### ISSUE THREAD

**Issue by MartinFromCodes** [junzew/HanTTS#3]
Centos下执行出错了,不知道怎么了

**Comment by junzew** [comment]
有stack trace之类的吗？

**Comment by junzew** [comment]
@MartinFromCodes CentOS下，[pyAudio](http://people.csail.mit.edu/hubert/pyaudio/) 这个库不能用pip安装，请直接用yum install。

[pyaudio package 下载](https://rpms.remirepo.net/rpmphp/zoom.php?rpm=pyaudio)

**Comment by MartinFromCodes** [comment]
好的我试试
